services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "userinfo"
      MYSQL_ROOT_PASSWORD: "1234"

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
