spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID
            client-secret: SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET
            client-authentication-method: client_secret_post
            scope:
              - email

            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
          kakao:

            client-id: SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID
            client-secret: SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
            client-name: Kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code

          google:
            clientId: SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
            clientSecret: SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

jwt:
  secretKey: JWT_SECRET_KEY

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
