global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [
        'prometheus:9090',
        #       'localhost:9090',
        #       '127.0.0.1:9090',
        #'host.docker.internal:9090'
      ]
  - job_name: 'backend'
    static_configs:
      - targets: [
        #'host.docker.internal:8080',
        'backend:8080',
      ]


  - job_name: 'node-exporter'
    static_configs:
      - targets: [
        'host.docker.internal:9100'
#        'node-exporter:9100'
      ]

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

