name: Backend CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mysqldb:
        image: mysql:8.0
        container_name: mysqldb
        ports:
          - "3307:3306"
        environment:
          MYSQL_DATABASE: moitda
          MYSQL_ROOT_PASSWORD: "1234"

      redis:
        container_name: redis
        image: redis
        restart: always
        ports:
          - "6379:6379"

      nginx:
        image: nginx:latest
#        volumes:
#          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

#      - name: Run tests
#        run: ./gradlew test
#
#      - name: Build Docker images
#        run: |
#          docker build -t myapp/spring-boot-app .
#          docker build -t myapp/nginx ./nginx
#
#      - name: Run Docker Compose
#        run: docker-compose up --build -d