name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:8.0
        container_name: mysqldb
        ports:
          - "3307:3306"
        environment:
          MYSQL_DATABASE: moitda
          MYSQL_ROOT_PASSWORD: "1234"
      redis:
        container_name: redis
        image: redis
        restart: always
        ports:
          - "6379:6379"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Build with Gradle
#        run: ./gradlew build

      ## gradle caching (빌드 시간 줄이기)
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradle chmod
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle build
      - name: Build with Gradle
        run: ./gradlew clean build -x test

#      - name: Trigger Docker CI/CD
#        run: |
#          curl -X POST -H "Authorization: token ${{ secrets.TOKEN }}" \
#          -H "Accept: application/vnd.github.v3+json" \
#          https://api.github.com/repos/2024-Team-Techeer-Salon/Moitda-Docker/dispatches \
#          -d '{"event_type":"backend_updated"}'
